import 'package:flutter/material.dart';
import 'package:movie_app_pakhrinsolthi/custom_widgets/single_movie_widget.dart';

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: appBar(),
      body: SingleChildScrollView(
        child: containerForMainBody(),
      ),
    );
  }

  Container containerForMainBody() {
    return Container(
      decoration: const BoxDecoration(
        image: DecorationImage(
          fit: BoxFit.fill,
          image: AssetImage('assets/images/bg.jpg'),
        ),
      ),
      child: Column(
        children: const [
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
          CustomMovieWidget(image: 'assets/images/wk.jpg'),
          CustomMovieWidget(image: 'assets/images/banner.png'),
        ],
      ),
    );
  }

  AppBar appBar() {
    return AppBar(
      title: Text(widget.title),
      centerTitle: true,
      elevation: 0,
      backgroundColor: Colors.black,
    );
  }
}
